"use client";

import { useState } from "react";
import { useCoverLetters } from "@/hooks/useCoverLetters";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import api from "@/lib/api";
import { Card, CardContent, CardHeader } from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import Modal from "@/components/ui/Modal";
import { Mail, Loader2, Eye, Trash2 } from "lucide-react";
import { formatDate } from "@/lib/utils";
import type { CoverLetter } from "@/types";

export default function CoverLettersPage() {
  const [page, setPage] = useState(0);
  const { data, isLoading } = useCoverLetters(page);
  const queryClient = useQueryClient();
  const [viewing, setViewing] = useState<CoverLetter | null>(null);

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      await api.delete(`/cover-letters/${id}`);
    },
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ["cover-letters"] }),
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Cover Letters</h1>
        <p className="text-gray-500">
          AI-generated cover letters for your applications
        </p>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-indigo-600" />
        </div>
      ) : data?.content && data.content.length > 0 ? (
        <div className="space-y-3">
          {data.content.map((cl) => (
            <Card key={cl.id}>
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="font-semibold text-gray-900">
                      {cl.jobTitle || "Untitled"}
                    </h3>
                    <p className="text-sm text-gray-500">
                      {cl.company} &middot; {formatDate(cl.createdAt)}
                      &middot;{" "}
                      <Badge className="bg-gray-100 text-gray-600">
                        {cl.aiProvider}
                      </Badge>
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setViewing(cl)}
                    >
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => deleteMutation.mutate(cl.id)}
                    >
                      <Trash2 className="h-4 w-4 text-red-500" />
                    </Button>
                  </div>
                </div>
                <p className="text-sm text-gray-600 mt-2 line-clamp-2">
                  {cl.content.substring(0, 200)}...
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="text-center py-16">
          <Mail className="h-12 w-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-1">
            No cover letters yet
          </h3>
          <p className="text-gray-500">
            Generate one by finding a job and clicking &quot;Quick Apply&quot;
          </p>
        </div>
      )}

      {/* View Modal */}
      <Modal
        open={!!viewing}
        onClose={() => setViewing(null)}
        title={viewing ? `Cover Letter - ${viewing.jobTitle}` : ""}
      >
        {viewing && (
          <div className="max-h-96 overflow-y-auto">
            <p className="text-sm text-gray-500 mb-3">
              {viewing.company} &middot; Generated by {viewing.aiProvider}
            </p>
            <div className="text-sm text-gray-700 whitespace-pre-line">
              {viewing.content}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
